version: '3.9'

services:
  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - users
      - posts
      - write
    volumes:
      - ./media:/app/media

  users:
    build: ./users
    ports:
      - "8001:8000"
    env_file: .env

  posts:
    build: ./posts
    ports:
      - "8002:8000"
    volumes:
      - ./media:/app/media
    env_file: .env

  write:
    build: ./write
    ports:
      - "8003:8000"
    volumes:
      - ./media:/app/media
    env_file: .env

  comments:
    build: ./comments
    ports:
      - "8005:8000"
    volumes:
      - ./comments:/app
    env_file: .env